sudo: false
language: go
services:
- docker
go:
- "1.14"
matrix:
  fast_finish: true
before_install:
# kubectl, kind
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
- go get -u github.com/onsi/ginkgo/ginkgo
- curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
script:
- make e2e
